services:
  database:
    image: postgres
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - path: .env
        required: true
    volumes:
      - api-counter-press:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABSE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: api-counter-press
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/local/app/src
        - path: ./src/package.json
          action: rebuild
volumes:
  api-counter-press:
